services:
  cliente-db:
    container_name: ms-cliente-db
    image: postgres:16
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ms_cliente
      POSTGRES_USER: ms_cliente
      POSTGRES_PASSWORD: ms_cliente
    volumes:
      - cliente_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ms_cliente -d ms_cliente"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - banco-network

  ms-cliente:
    build:
      context: ./ms-cliente
    container_name: ms-cliente
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://cliente-db:5432/ms_cliente
      SPRING_DATASOURCE_USERNAME: ms_cliente
      SPRING_DATASOURCE_PASSWORD: ms_cliente
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
    depends_on:
      cliente-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - banco-network

  cuenta-db:
    container_name: ms-cuenta-db
    image: postgres:16
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: ms_cuenta
      POSTGRES_USER: ms_cuenta
      POSTGRES_PASSWORD: ms_cuenta
    volumes:
      - cuenta_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ms_cuenta -d ms_cuenta"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - banco-network

  ms-cuenta:
    build:
      context: ./ms-cuenta
    container_name: ms-cuenta
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://cuenta-db:5432/ms_cuenta
      SPRING_DATASOURCE_USERNAME: ms_cuenta
      SPRING_DATASOURCE_PASSWORD: ms_cuenta
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
    depends_on:
      cuenta-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - banco-network

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - banco-network

volumes:
  cliente_db_data:
  cuenta_db_data:

networks:
  banco-network:
    driver: bridge