version: '3'

services:
  client-db:
    container_name: ms-client-db
    image: postgres:16
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ms_client
      POSTGRES_USER: ms_client
      POSTGRES_PASSWORD: ms_client
    volumes:
      - ./postgres:/var/lib/postgresql/data