server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: ms-cliente
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/ms_client}
    username: ${SPRING_DATASOURCE_USERNAME:ms_client}
    password: ${SPRING_DATASOURCE_PASSWORD:ms_client}
    driver-class-name: org.postgresql.Driver
  jap:
    hibernate:
      ddl-auto: ${SPRING_JPA_DDL_AUTO:update}
    properties:
      hibernate:
        format_dql: true
    show-sql: false
