server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: ms-cliente
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/ms_cliente}
    username: ${SPRING_DATASOURCE_USERNAME:ms_cliente}
    password: ${SPRING_DATASOURCE_PASSWORD:ms_cliente}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_DDL_AUTO:update}
    properties:
      hibernate:
        format_sql: true
    show-sql: false

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}

management:
  endpoints:
    web:
      exposure:
        include: info

logging:
  level:
    com.banco.mscliente: INFO